-- SkillSync Supabase Schema
-- Enable required extensions
create extension if not exists "uuid-ossp";
create extension if not exists vector;

-- Auth: We will use Supabase Auth users table (auth.users). We'll mirror minimal profile data.

-- Enums
create type public.user_role as enum ('student','company','admin');
create type public.application_status as enum ('applied','shortlisted','rejected','hired');

-- Profiles table for all users
create table if not exists public.profiles (
  id uuid primary key default uuid_generate_v4(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  role public.user_role not null,
  email text not null,
  display_name text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_profiles_role on public.profiles(role);

-- Students
create table if not exists public.students (
  id uuid primary key default uuid_generate_v4(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  university text,
  degree text,
  graduation_year int,
  resume_url text,
  bio text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Companies
create table if not exists public.companies (
  id uuid primary key default uuid_generate_v4(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  name text not null,
  website text,
  description text,
  logo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_companies_name on public.companies using gin (to_tsvector('english', name));

-- Skills
create table if not exists public.skills (
  id bigserial primary key,
  name text not null unique
);

-- Student skills
create table if not exists public.student_skills (
  student_id uuid not null references public.students(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  level int default 1 check (level between 1 and 5),
  primary key (student_id, skill_id)
);

-- Internship listings
create table if not exists public.internships (
  id uuid primary key default uuid_generate_v4(),
  company_id uuid not null references public.companies(id) on delete cascade,
  title text not null,
  description text not null,
  location text,
  is_remote boolean default true,
  stipend numeric,
  openings int default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_internships_title on public.internships using gin (to_tsvector('english', title));

-- Internship required skills
create table if not exists public.internship_skills (
  internship_id uuid not null references public.internships(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  weight int default 1 check (weight between 1 and 5),
  primary key (internship_id, skill_id)
);

-- Applications
create table if not exists public.applications (
  id uuid primary key default uuid_generate_v4(),
  internship_id uuid not null references public.internships(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status public.application_status default 'applied',
  cover_letter text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (internship_id, student_id)
);
create index if not exists idx_applications_status on public.applications(status);

-- Embeddings store using pgvector (768 dims for Gemini text-embedding-004; adjust as needed)
create table if not exists public.embeddings (
  id bigint generated by default as identity primary key,
  owner_type text not null check (owner_type in ('student_resume','internship')),
  owner_id uuid not null,
  content text not null,
  embedding vector(768) not null,
  metadata jsonb default '{}',
  created_at timestamptz default now()
);
create index if not exists idx_embeddings_owner on public.embeddings(owner_type, owner_id);
create index if not exists idx_embeddings_vec on public.embeddings using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Materialized views / analytics (simplified)
create materialized view if not exists public.analytics_overview as
select
  (select count(*) from public.profiles) as total_users,
  (select count(*) from public.students) as total_students,
  (select count(*) from public.companies) as total_companies,
  (select count(*) from public.internships) as total_internships,
  (select count(*) from public.applications) as total_applications;

-- Similarity search helper functions
create or replace function public.match_internships_for_student(p_student_id uuid, p_limit int default 10)
returns table (internship_id uuid, score float)
language sql stable as $$
  with q as (
    select embedding from public.embeddings
    where owner_type = 'student_resume' and owner_id = p_student_id
    order by created_at desc limit 1
  )
  select e.owner_id as internship_id,
         1 - (e.embedding <=> q.embedding) as score
  from public.embeddings e, q
  where e.owner_type = 'internship'
  order by e.embedding <=> q.embedding
  limit p_limit;
$$;

create or replace function public.match_students_for_internship(p_internship_id uuid, p_limit int default 10)
returns table (student_id uuid, score float)
language sql stable as $$
  with q as (
    select embedding from public.embeddings
    where owner_type = 'internship' and owner_id = p_internship_id
    order by created_at desc limit 1
  )
  select e.owner_id as student_id,
         1 - (e.embedding <=> q.embedding) as score
  from public.embeddings e, q
  where e.owner_type = 'student_resume'
  order by e.embedding <=> q.embedding
  limit p_limit;
$$;

-- Basic RLS policies (adjust per your needs)
alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.companies enable row level security;
alter table public.internships enable row level security;
alter table public.internship_skills enable row level security;
alter table public.skills enable row level security;
alter table public.student_skills enable row level security;
alter table public.applications enable row level security;
alter table public.embeddings enable row level security;

-- Example permissive policies (tighten in production)
create policy if not exists "Profiles are viewable by owners" on public.profiles
for select using (auth.uid() = auth_user_id);
create policy if not exists "Students are viewable by owner" on public.students
for select using (exists (select 1 from public.profiles p where p.id = students.profile_id and p.auth_user_id = auth.uid()));
create policy if not exists "Companies viewable by owner" on public.companies
for select using (exists (select 1 from public.profiles p where p.id = companies.profile_id and p.auth_user_id = auth.uid()));
create policy if not exists "Internships are public" on public.internships for select using (true);
create policy if not exists "Applications by owner or company" on public.applications for select using (
  exists (
    select 1 from public.students s join public.profiles p on p.id = s.profile_id
    where s.id = applications.student_id and p.auth_user_id = auth.uid()
  )
  or exists (
    select 1 from public.internships i join public.companies c on c.id = i.company_id join public.profiles p2 on p2.id = c.profile_id
    where i.id = applications.internship_id and p2.auth_user_id = auth.uid()
  )
);
create policy if not exists "Embeddings selectable by owner" on public.embeddings for select using (
  (owner_type = 'student_resume' and exists (
    select 1 from public.students s join public.profiles p on p.id = s.profile_id
    where s.id = embeddings.owner_id and p.auth_user_id = auth.uid()
  ))
  or (owner_type = 'internship' and exists (
    select 1 from public.internships i join public.companies c on c.id = i.company_id join public.profiles p on p.id = c.profile_id
    where i.id = embeddings.owner_id and p.auth_user_id = auth.uid()
  ))
);

-- Upsert helper function for skills
create or replace function public.ensure_skill(p_name text) returns bigint language plpgsql as $$
declare sid bigint;
begin
  insert into public.skills(name) values (p_name)
  on conflict (name) do update set name = excluded.name
  returning id into sid;
  return sid;
end; $$;

-- Admin utility to refresh analytics materialized view
create or replace function public.refresh_analytics() returns void language sql security definer as $$
  refresh materialized view public.analytics_overview;
$$;
